language: 'ruby'
rvm:
  - '2.1.1'

services:
  - elasticsearch

before_install:
  - "sudo apt-get install -y libicu-dev"

before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - "cp config/database.yml.postgresql config/database.yml"
  - "cp config/application.yml.sample config/application.yml"
  - "RAILS_ENV=test ./bin/rake db:create db:migrate"

script:
  - "./bin/rake spec"
