language: 'ruby'
rvm:
  - '2.0.0'
bundler_args: "--without development"
before_script:
  - "apt-get install libicu-dev"
  - "cp config/database.yml.postgresql config/database.yml"
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script: "bundle exec rake spec"
