language: 'ruby'
rvm:
  - '2.0.0'

install:
  - "sudo apt-get install -y libicu-dev"

bundler_args: "--without development"
before_script:
  - "cp config/database.yml.postgresql config/database.yml"
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script: "bundle exec rake spec"
