language: 'ruby'
rvm:
  - '2.0.0'

install:
  - "sudo apt-get install -y libicu-dev"

before_script:
  - bundle install --without development
  - "cp config/database.yml.postgresql config/database.yml"
  - "cp config/application.yml.sample config/application.yml"
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script: "bundle exec rake spec"
